version: "3"
services:
  www:
    container_name: www
    restart: always
    build: ./
    ports:
      - "80:80"
    volumes:
      - /home/furenku/Music/punksnotdev/WWW/LANDING:/usr/share/nginx/html
volumes:
  LANDING: