version: "3"
services:
  www:
    container_name: www
    restart: always
    build: ./
    # build:
      # context: ./
    ports:
      - "80:80"
    volumes:
      - ./LANDING:/usr/share/nginx/html

volumes:
  LANDING: